version: '3.8'
services:
  my_api:
    container_name: my_api
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - '3010:3010'
    command: npm run start
    env_file:
      - .env
    depends_on:
      - postgresql_db_latest

  postgresql_db_latest:
    container_name: postgresql_db_latest
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: "postgresql_db_latest"
      POSTGRES_USER: "user_postgresql_db_latest"
      POSTGRES_PASSWORD: "postgresql"
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  pgdata: